steps:
  - name: 'josecyber/cloudbuild_image'
    id: Environment
    entrypoint: bash
    args: 
      - -c
      - |
        echo $REPO_NAME
        echo $BRANCH_NAME
        echo $SHORT_SHA
        env > /workspace/build_vars
    waitFor: [-]

  - name: 'josecyber/cloudbuild_image'
    id: Git Clone
    entrypoint: bash
    allow_failure: true
    args: 
      - -c
      - |
        source /workspace/build_vars 
        
        echo "git clone" | figlet

        git_user=$(echo $REPO_NAME | cut -d"_" -f2)
        project_name=$(echo $REPO_NAME | cut -d"_" -f3)
        echo 'Git Clone' | figlet 
        
        git clone https://$git_user:$git_token@github.com/$git_user/$project_name

        if [ -d $project_name ];then
           echo 'repositorio clonado'
        else
           echo 'erro ao clonar repositorio' | figlet
        fi 

        env > /workspace/build_vars
    secretEnv: ['git_token']
    waitFor: [Environment]
  
  - name: 'josecyber/cloudbuild_image'
    id: Docker build
    entrypoint: bash
    args: 
      - -c
      - |
        source /workspace/build_vars 
        
        echo $project_name

        echo 'docker build' | figlet 
        docker build -t $project_name -f $project_name/src/dockerfile .
           
    waitFor: [Git Clone]

  - name: 'josecyber/cloudbuild_image'
    id: Docker vulnarability
    entrypoint: bash
    args: 
      - -c
      - |
        echo 'docker vulnarability'
    waitFor: [Docker build]
  
  - name: 'josecyber/cloudbuild_image'
    id: Docker push
    entrypoint: bash
    args: 
      - -c
      - |
        source /workspace/build_vars 

        echo 'Docker Push' | figlet
        
        echo $dockerhub_psw > senha.txt
        cat senha.txt | docker login --username=$dockerhub_usr --password-stdin
          
        docker tag $project_name  $dockerhub_usr/$project_name
        docker push $dockerhub_usr/$project_name

    secretEnv: ['dockerhub_usr', 'dockerhub_psw']
    waitFor: [Docker vulnarability]
  
  - name: 'josecyber/cloudbuild_image'
    id: Kubecost
    entrypoint: bash
    args: 
      - -c
      - |
        echo 'kubecost Analasys' | filget
    waitFor: [Docker push]

availableSecrets:
  secretManager:
  - versionName: projects/164405315743/secrets/dockerhub_psw/versions/1
    env: 'dockerhub_psw'
  - versionName: projects/164405315743/secrets/dockerhub_usr/versions/1
    env: 'dockerhub_usr'
  - versionName: projects/164405315743/secrets/git_token/versions/1
    env: 'git_token'

timeout: 2500s