steps:
  - name: 'josecyber/cloudbuild_image'
    id: Environment
    entrypoint: bash
    args: 
      - -c
      - |
        echo $REPO_NAME
        echo $BRANCH_NAME
        echo $SHORT_SHA
    waitFor: []

  - name: 'josecyber/cloudbuild_image'
    id: Git Clone
    entrypoint: bash
    args: 
      - -c
      - |
        
        git_user=$(echo $REPO_NAME | cut -d"_" -f2)
        project_name=$(echo $REPO_NAME | cut -d"_" -f3)

        echo 'Git Clone' | figlet 

        git clone https://$git_user:$GITTOKEN@github.com/$git_user/$project_name
    
    secretEnv: ['GITTOKEN']
  
  - name: 'josecyber/cloudbuild_image'
    id: Docker build
    entrypoint: bash
    args: 
      - -c
      - |
        echo 'Docker build' | figlet 
        cd $project_name
        docker build -t chapter_sysadmin -f /src/dockerfile .
    waitFor: [Git Clone]

  - name: 'josecyber/cloudbuild_image'
    id: Docker vulnarability
    entrypoint: bash
    args: 
      - -c
      - |
        echo $REPO_NAME
    waitFor: [Docker build]
  
  - name: 'josecyber/cloudbuild_image'
    id: Docker push
    entrypoint: bash
    args: 
      - -c
      - |
        echo 'Docker Push' | figlet
        docker tag josecyber/cloudbuild_image:$SHORT_SHA
        docker push josecyber/cloudbuild_image:$SHORT_SHA

    secretEnv: ['DOCKERHUB_USR', 'DOCKERHUB_PWD']
    waitFor: [Docker vulnarability]
  
  - name: 'josecyber/cloudbuild_image'
    id: Kubecost
    entrypoint: bash
    args: 
      - -c
      - |
        echo 'kubecost Analasys' | filget
    waitFor: [Docker push]

availableSecrets:
  secretManager:
  - versionName: projects/164405315743/secrets/DOCKERHUB_PWD/versions/1
    env: 'DOCKERHUB_PWD'
  - versionName: projects/164405315743/secrets/DOCKERHUB_USR/versions/1
    env: 'DOCKERHUB_USR'
  - versionName: projects/164405315743/secrets/GITTOKEN/versions/1
    env: 'GITTOKEN'
