apiVersion: v1
kind: Service
metadata:
  name: teste-svc
  namespace: 2rpnet
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: webserver
      port: 80
  selector:
    app:  2rpweb-server