apiVersion: v1
kind: Service
metadata:
  name: chapter-sysadmin-svc
  namespace: chapter
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: webserver
      port: 8080
  selector:
    app: chapter-sysadmin