apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter-sysadmin-dp
  namespace: chapter
  labels:
    app: chapter-sysadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter-sysadmin
  template:
    metadata:
      labels:
        app: chapter-sysadmin
    spec:
      containers:
      - name: chapter-sysadmin-container
        image: josecyber/chapter-sysadmin
        envFrom:
        - secretRef:
            name: chapter-sysadmin-es

         