FROM node:latest

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app


COPY . .

RUN pwd && ls -l

RUN npm install

COPY --chown=node:node . .

USER node

CMD [ "node", "server.js" ]